baseURL: https://fangchen-portfolio.netlify.app/
languageCode: en-us
title: portfolio website for Fangchen Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
    
    title: Hi, my name is Fangchen and I am a student at London Business School.
  blog: {}
  contact:
    address:
      - city: London, NW1 6AP
        country: London
        street: Clarence Gate Gardens
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: fwang.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44)07778820456
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100010054565496
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/fangchen.w/
      - icon: fa-github
        label: GitHub
        url: https://github.com/ferencWANG
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/fangchenwang/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Masters in Analytics and Management
        title: London Business School
        url: blogs/
      - image: wfc.jpg
        subtitle: 
        title: About myself
        url: docs/CV.pdf
      - image: risk.png
        subtitle: Risk-Return of DJIA stocks
        title: Introductory data analytics example
        url: blogs/risk_return
      - image: brexit.png
        subtitle: An analysis on Brexit vote result
        title: Brexit vote analysis
        url: blogs/brexit
      - image: animal.png
        subtitle: Animal rescue incidents attended by the London Fire Brigade
        title: Animal rescue analysis
        url: blogs/animal
      - image: life.png
        subtitle: comparing countries on different continents Gapminder dataset
        title: Life expectancy analysis over time
        url: blogs/country
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hey there! My name is Fangchen and I am Out in Business Merit Scholar of London Business School Masters in Analytics and Management Class of 2023 cohort.
              I did my undergrad at Nanjing University in the dual degree program of Computer Science and Financial Engineering, with minors in Spanish and English literature.
            I am passionate about language learning, tennis, volunteering, and Chinese traditional calligraphy. 
            I played for Nanjing University Varsity Tennis Team for three years, and I volunteered with an American NPO, Learning Enterprises, for three years, during which my team and I helped children from underdeveloped regions in China, Romania, and Panama to learn more about the world through English teaching. \r\n"
    title: Fangchen Wang
    url: blogs
